export const CURRENT_QUESTION_BANK_FILES = [
  "content/items/competencias_ciudadanas/ciudadanas-participacion-001.md",
  "content/items/competencias_ciudadanas/ciudadanas-participacion-002.md",
  "content/items/competencias_ciudadanas/ciudadanas-pluralidad-diversidad-001.md",
  "content/items/competencias_ciudadanas/ciudadanas-responsabilidad-democratica-001.md",
  "content/items/competencias_ciudadanas/ciudadanas-responsabilidad-democratica-002.md",
  "content/items/gestion/gestion-gestion-academica-001.md",
  "content/items/gestion/gestion-gestion-academica-002.md",
  "content/items/gestion/gestion-planeacion-institucional-001.md",
  "content/items/gestion/gestion-seguimiento-mejora-001.md",
  "content/items/gestion/gestion-seguimiento-mejora-002.md",
  "content/items/lectura_critica/lectura-critica-analisis-argumentativo-001.md",
  "content/items/lectura_critica/lectura-critica-analisis-argumentativo-002.md",
  "content/items/lectura_critica/lectura-critica-estructura-textual-001.md",
  "content/items/lectura_critica/lectura-critica-interpretacion-textual-001.md",
  "content/items/matematicas/matematicas-analisis-datos-002.md",
  "content/items/matematicas/matematicas-resolucion-problemas-001.md",
  "content/items/matematicas/matematicas-resolucion-problemas-002.md",
  "content/items/normatividad/normatividad-convivencia-escolar-001.md",
  "content/items/normatividad/normatividad-convivencia-escolar-002.md",
  "content/items/normatividad/normatividad-evaluacion-normativa-001.md",
  "content/items/normatividad/normatividad-funcion-docente-001.md",
  "content/items/normatividad/normatividad-inclusion-001.md",
  "content/items/pedagogia/pedagogia-evaluacion-aprendizaje-001.md",
  "content/items/pedagogia/pedagogia-evaluacion-aprendizaje-002.md",
  "content/items/pedagogia/pedagogia-inclusion-001.md",
  "content/items/pedagogia/pedagogia-inclusion-002.md",
  "content/items/pedagogia/pedagogia-planeacion-aula-001.md",
] as const;

export const EXPECTED_ACTIVE_CORPUS_COUNT = 27;
